// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pluto.netcoreTemplate.Infrastructure;

namespace Pluto.netcoreTemplate.API.Migrations
{
    [DbContext(typeof(PlutonetcoreTemplateDbContext))]
    partial class PlutonetcoreTemplateDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("Relational:Sequence:dbo.userbookseq", "'userbookseq', 'dbo', '1', '10', '', '', 'Int64', 'False'")
                .HasAnnotation("Relational:Sequence:dbo.userseq", "'userseq', 'dbo', '1', '10', '', '', 'Int64', 'False'")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Pluto.netcoreTemplate.Domain.Entities.UserAggregate.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:HiLoSequenceName", "userseq")
                        .HasAnnotation("SqlServer:HiLoSequenceSchema", "dbo")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.SequenceHiLo);

                    b.Property<DateTime>("CreateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2019, 12, 31, 19, 5, 48, 878, DateTimeKind.Local).AddTicks(8908));

                    b.Property<DateTime>("EditTime")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2019, 12, 31, 19, 5, 48, 882, DateTimeKind.Local).AddTicks(1088));

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("_tel")
                        .HasColumnName("Tel")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("_userName")
                        .HasColumnName("UserName")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.HasKey("Id");

                    b.ToTable("Users","dbo");
                });

            modelBuilder.Entity("Pluto.netcoreTemplate.Domain.Entities.UserAggregate.UserBook", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:HiLoSequenceName", "userbookseq")
                        .HasAnnotation("SqlServer:HiLoSequenceSchema", "dbo")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.SequenceHiLo);

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("_bookName")
                        .HasColumnName("BookName")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<decimal>("_price")
                        .HasColumnName("Price")
                        .HasColumnType("decimal(8, 2)");

                    b.HasKey("Id")
                        .HasAnnotation("SqlServer:Identity", "1,1");

                    b.HasIndex("UserId");

                    b.ToTable("UserBooks","dbo");
                });

            modelBuilder.Entity("Pluto.netcoreTemplate.Domain.Entities.UserAggregate.UserBook", b =>
                {
                    b.HasOne("Pluto.netcoreTemplate.Domain.Entities.UserAggregate.User", "User")
                        .WithMany("UserBookItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
